version: 2
jobs:
  build:
    docker:
      - image: golang:1.10
    working_directory: /go/src/github.com/kulinacs/nmap
    steps:
      - checkout
      - run:
          name: Run tests
          command: go test
